In [29]:
import numpy as np
def interw(dw,safes):
    s=[]
    shapes=[]
    m,n = dw.shape
    print(dw.shape)
    for i in range(m):
        for j in range(n):
            x=0
            subs = np.array(safes[i,j])
            shapes.append(subs.shape[0])
            for k in range(subs.shape[0]):
                x+=(subs[k,1]-subs[k,0])/dw[i,j]
            s.append(x)
    s= np.array(s)
    shapes=np.array(shapes)
    print('shapesw:',np.min(shapes),np.max(shapes))
    print(shapes)
    return np.min(s)
def interb(dw,safes):
    s=[]
    shapes=[]
    m= dw.shape[0]
    for i in range(m):
        x=0
        subs = np.array(safes[i])
        shapes.append(subs.shape[0])
        for k in range(subs.shape[0]):
            x+=(subs[k,1]-subs[k,0])/(dw[i]*2)
        s.append(x)
    s= np.array(s)
    shapes=np.array(shapes)
    print('shapesb:',np.min(shapes),np.max(shapes))
    print(shapes)
    return np.min(s)
def inter_meanw(dw,mw,safes):
    s=[]
    m,n = dw.shape
    for i in range(m):
        for j in range(n):
            x=0
            subs = np.array(safes[i,j])
            for k in range(subs.shape[0]):
                # x+=(subs[k,1]-subs[k,0])/dw[i,j]
                if subs[k,0]<=mw[i,j] and subs[k,1]>=mw[i,j]:
                    s.append([subs[k,0],subs[k,1]])
    s= np.array(s)
    return s
def inter_meanb(dw,mw,safes):
    s=[]
    m= dw.shape[0]
    for i in range(m):
        x=0
        subs = np.array(safes[i])
        for k in range(subs.shape[0]):
            # x+=(subs[k,1]-subs[k,0])/(dw[i]*2)
                if subs[k,0]<=mw[i] and subs[k,1]>=mw[i]:
                    s.append([subs[k,0],subs[k,1]])
        # s.append(x)
    s= np.array(s)
    return s

for id in ['lds','pend','car']:
    # path = f'./data/{id}/weights/min_{id}.npz'
    # path1 = f'./data/{id}/weights/safeWeight_{id}.npz'
    path = f'./data/{id}/weights/{id}_all.npz'
    path1 = f'./data/{id}/weights/safeWeight_{id}_all.npz'
    res=np.load(path,allow_pickle=True)
    mW_0, mb_0, mW_1, mb_1, dW_0, db_0, dW_1, db_1=res['mW_0'],res['mb_0'],res['mW_1'],res['mb_1'],res['dW_0'],res['db_0'],res['dW_1'],res['db_1']
    # mW_1, mb_1, dW_1, db_1=res['mW_1'],res['mb_1'],res['dW_1'],res['db_1']
    res=np.load(path1,allow_pickle=True)
    safeW0,safeB0,safeW1,safeB1 = res['safeW0'],res['safeB0'],res['safeW1'],res['safeB1']
    # safeW1,safeB1 = res['safeW1'],res['safeB1']
    s1= interw(dW_0,safeW0)
    s2= interw(dW_1,safeW1)
    s3 = interb(db_0,safeB0)
    s4 =interb(db_1,safeB1)
    # final = np.array([s1,s2,s3,s4])
    # print("id:",id,"_",np.min(final))
    print("id",id,s2.shape)
    # s4 = np.concatenate((s3,s4),axis=0)
    # num =(mW_0.shape[0]+1)*16+17
    # print('S_{\mu_{all}}=&~',end ="")
    # for i in range(4):
    #     print("[%.3f,%.3f]_%d \\times "%(s2[i,0],s2[i,1],i+1),end ="")
    # print('...\\\ &\\times',end =" ")
    # for i in range(2,-1,-1):
    #     print("[%.3f,%.3f]_{%d} \\times "%(s4[-i,0],s4[-i,1],num-i),end ="")
    # print(' ')

(4, 16)
shapesw: 1 6
[4 2 4 2 3 3 3 4 3 6 4 2 5 4 4 3 4 5 2 4 2 3 4 3 5 5 4 2 4 5 2 3 3 2 2 4 4
 5 4 2 5 3 2 3 4 2 3 2 4 3 2 3 2 3 2 5 2 2 3 4 2 1 4 3]
(16, 1)
shapesw: 2 5
[2 3 3 3 5 2 3 4 4 4 3 4 3 3 4 3]
shapesb: 2 4
[4 2 4 2 2 3 2 4 3 3 4 4 2 2 4 3]
shapesb: 3 3
[3]
id lds ()
(4, 16)
shapesw: 1 6
[2 3 2 5 3 2 2 3 3 3 1 2 2 2 3 3 1 4 3 4 3 4 3 3 4 3 4 3 3 3 3 3 5 2 3 4 2
 2 2 2 6 3 3 5 2 2 5 4 3 3 5 4 2 2 3 4 3 2 3 2 6 3 2 5]
(16, 1)
shapesw: 2 5
[5 3 4 3 2 2 3 4 4 2 4 4 5 4 4 4]
shapesb: 1 4
[2 3 4 4 4 4 3 3 3 3 3 1 2 4 4 3]
shapesb: 4 4
[4]
id pend ()
(6, 16)
shapesw: 1 2
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
(16, 1)
shapesw: 1 2
[1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1]
shapesb: 1 2
[1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1]
shapesb: 1 1
[1]
id car ()
